version: '3'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./back
    ports:
      - "1880:1880"
    volumes:
      - ./back:/data
      - ./back/uploads:/data/uploads
    environment:
      - TZ=America/Sao_Paulo
